name: Price Watch (Nike)

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright.install --with-deps

      - name: Run watcher
        env:
          QUERY: ${{ secrets.QUERY }}
          THRESHOLD: ${{ secrets.THRESHOLD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SEND_SCREENSHOT_ALWAYS: ${{ secrets.SEND_SCREENSHOT_ALWAYS }}
        run: python -m src.main
